version: "3.9"
services:
  db:
    image: postgres:16
    platform: linux/arm64/v8       # host kamu arm64; hilangkan amd64 yg bikin warning
    container_name: peoplecount-db
    restart: unless-stopped
    env_file: .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro   # <-- LANGSUNG ke folder db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build: .
    image: peoplecounting-app:latest      # nama image sesuai tema project
    container_name: peoplecount-api
    restart: unless-stopped
    working_dir: /app
    env_file: .env
    environment:
      PYTHONPATH: /app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - latest_out:/app/samples/output
    command: >
      bash -lc "uvicorn app:app --host 0.0.0.0 --port 8080"

  worker:
    image: peoplecounting-app:latest
    container_name: peoplecount-worker
    restart: unless-stopped
    working_dir: /app
    env_file: .env
    environment:
      PYTHONPATH: /app
      ULTRALYTICS_CACHE_DIR: /app/.cache/ultralytics
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
    volumes:
      - ./:/app
      - latest_out:/app/samples/output
    command: ["python", "workers/detect_track_count.py", "--db-log"]

volumes:
  pgdata:
  latest_out: